### ISSUE TITLE
Set desired room temperature via luxtronik.write

### ISSUE THREAD

**Issue by werdlerk** [Bouni/luxtronik#43]
Hi @Bouni ,

Thank you for your hard work and this awesome component! I'm using it to read data from my Alpha Innotec WZSV62K3M heat pump and show it in Home Assistant. It's working wonderfully.

Some time ago, I've made automations to be able to set the heating and hot water mode to a different value (Automatic / Second heatsource / Party / Holidays) so I could suspend the heat pump when on vacation. This works wel..

Today, I was trying to set the desired room temperature of the living room but unfortunately, writing a different value to parameter `ID_WEB_RBE_RT_Soll` didn't work.

Request:
```
service: luxtronik.write
data:
  parameter: ID_WEB_RBE_RT_Soll
  value: "20"
```

Response:
```
2022-09-14 19:59:13.644 WARNING (SyncWorker_4) [Luxtronik.Parameters] Parameter 'ID_WEB_RBE_RT_Soll' not found
2022-09-14 19:59:13.661 WARNING (SyncWorker_4) [Luxtronik.Parameters] Parameter 'ID_WEB_RBE_RT_Soll' not found
```

I've double checked the parameter name with the parameters on the [Loxwiki page](https://loxwiki.atlassian.net/wiki/spaces/LOX/pages/1533935933/Java+Webinterface) but everything seems to be alright.

Can you help me set the desired room temperature via an automation ?

Thanks!

**Comment by Bouni** [comment]
This is because you try to write a **calculation**, the table below "3004 - Berechnungen lesen" on the loxwiki just shows calculations.

Ideally you take a look in the source of [python-luxtronik](https://github.com/Bouni/python-luxtronik/blob/main/luxtronik/parameters.py), which is the underlying python library of this custom component.

There is not much documentation what parameter dows what, so my way to figure things out is to read the current parameters using this python script: https://gist.github.com/Bouni/cf0dc2c7c53c32deeb264803ec350e5c

You need to install python-luxtronik first to be able to run it (`pip install luxtronik`) and set the right IP address in the script.

This will read all calculations, parameters and visibilities of your heatpump.

Lets say you know that you've set ID_WEB_RBE_RT_Soll from your heatpumps webinterface to 21°C.
Look for any value that has a value of 20.0 or 200 (if the type is unknown, no scaling is applied).
Then change the value to lets say 20.5°C in the webinterface, read again using the script and check which parameter changed to 20.5 / 205. 
That way you should be able to figure out which parameter is the right one.

If that parameter has no ` True),` at the end in the python-luxtronik source code you need to set `safe: false` in your configuration.yaml in order to writ that parameter.

If you figure out the parameter, let me know and I can make a change to apply scaling if neccessary and set the `True` in the lbrary.

**Comment by werdlerk** [comment]
Hi @Bouni , thank you for your quick response. 
I've run the script a couple times around changing the desired temperature but unfortunately the parameters didn't change, only the calculations. To me it seems like this can't be changed via the connection. 

You can see the script outputs in this gist: https://gist.github.com/werdlerk/eaab0a7c0285676ec610b92dbb239826

Thanks for the effort and thank you for the nice HA component 👍
